---
abstract: 'OASIS Web Services Security'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Compile-WSS
no_index:
  directory:
    - t
    - inc
requires:
  Digest::SHA1: 0
  Encode: 0
  File::Basename: 0
  Log::Report: 0.92
  MIME::Base64: 0
  Test::More: 0.54
  XML::Compile: 1.21
  XML::Compile::C14N: 0.10
  XML::Compile::Cache: 0.99
  XML::Compile::SOAP: 2.23
version: 0.91
