--- #YAML:1.0
name:               XML-Compile-WSS
version:            0.13
abstract:           OASIS Web Services Security
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::SHA1:         0
    Encode:               0
    File::Basename:       0
    Log::Report:          0.92
    Test::More:           0.54
    XML::Compile:         1.21
    XML::Compile::C14N:   0.10
    XML::Compile::Cache:  0.99
    XML::Compile::SOAP:   2.23
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
